default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: jamie_blog_dev

test:
  <<: *default
  database: jamie_blog_test

production:
  database: ENV{"DATABASE_URL"}